name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, lint, and Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Build, Test, and Lint
        uses: remedyred/build-and-test-action@v1.0.8
      - name: Verify Releasability
        uses: remedyred/release-please-action@v1.3.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DEBUG: true
          VERIFY_ONLY: true
