name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - name: Release
        uses: remedyred/release-please-action@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
